language: python

python:
  - "3.6.6"

addons:
  postgresql: "9.6"
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-10 postgresql-client-10
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - export PGPORT=5433
before_script:
  - psql -c 'create database ireporter_test;' -U postgres

install:
  - pip install -r requirements.txt

script:

  - python -m pytest --cov

after_success:
  - coveralls
